# File: GestiondesRéservationsdeSallesUniversitaires/docker-compose.yml
services:
  app:
    build: .
    image: reservation-salles-app:1.0
    container_name: reservation_salles_app
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - reservation_network

  db:
    image: postgres:16-alpine
    container_name: reservation_salles_db
    restart: always
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: reservation_salles
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation123
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reservation_user -d reservation_salles"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - reservation_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: reservation_salles_pgadmin
    restart: always
    env_file:
      - .env.docker
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mohidine.sn
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - reservation_network

volumes:
  pg_data:

networks:
  reservation_network:
    driver: bridge
