
services:
  app:
    build: .
    image: reservation-salles-app:1.0
    container_name: reservation_salles_app
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
    networks:
      - reservation_network

  webserver:
    image: nginx:stable-alpine
    container_name: reservation_salles_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - reservation_network

  db:
    image: mysql:8.0
    container_name: reservation_salles_db
    restart: always
    env_file:
      - .env.docker
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - reservation_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: reservation_salles_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    networks:
      - reservation_network

volumes:
  db_data:

networks:
  reservation_network:
    driver: bridge