#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Application;
use Dotenv\Dotenv;

require __DIR__ . '/vendor/autoload.php';

Dotenv::createImmutable(__DIR__)->safeLoad();

$driver = $_ENV['DB_DRIVER'] ?? 'pgsql';
$defaultPort = ($driver === 'pgsql') ? 5432 : 3306;

$config = [
    'driver' => $driver,
    'host' => $_ENV['DB_HOST'] ?? '127.0.0.1',
    'port' => (int) ($_ENV['DB_PORT'] ?? $defaultPort),
    'database' => $_ENV['DB_DATABASE'] ?? 'reservation_salles',
    'username' => $_ENV['DB_USERNAME'] ?? ($driver === 'pgsql' ? 'postgres' : 'root'),
    'password' => $_ENV['DB_PASSWORD'] ?? '',
];

$configureDatabase = require __DIR__ . '/config/database.php';
$capsule = $configureDatabase($config);

exit((new Application($capsule))->run($argv));
